### ISSUE TITLE
Manipulating series counters between environments?

### ISSUE THREAD

**Issue by svlauer** [jbezos/enumitem#25]
As per the documentation, when a cloned list `foo` is created with type `enumerate`, the counters  `fooi`, `fooii`, `fooiii` ... are created.

Is there an equivalent for environments that use a series? I.e., if I create a series and use `resume=foobar`, I assume that there is some counter that keeps track of the value for the series. What is the name of that counter?

(My usecase: Making a list that uses a series work with  [`beamer`](https://ctan.org/pkg/beamer)'s overlay feature. This feature will lead to certain parts of a "frame" (roughy, page) to be typeset multiple times. `beamer` provides facilities to reset counters for each re-typeset, but for using those, I need to know the name of the counter, obviously.)

**Comment by muzimuzhi** [comment]
> I.e., if I create a series and use `resume=foobar`, I assume that there is some counter that keeps track of the value for the series. What is the name of that counter?

The "value" is not stored in a counter, but in a macro `\enit@resume@<env name>` as part of a count assignment. For example, in the following example, after the first `enumerate` env, the two resume macros are defined by
```tex
\def \enit@resumekeys@enumerate {}%
\def \enit@resume@enumerate {\c@enumi 2}
```
By calling the second one at the beginning of the second `enumerate` env with option `resume`, the value of counter `enumi` is restored. See the [definition of `\enit@endlist`](https://github.com/jbezos/enumitem/blob/1bdcad0987823b3716c86b126b3863f895ea9c4a/enumitem.sty#L1107-L1123).

```tex
\documentclass{article}
\usepackage{enumitem}

\begin{document}
\begin{enumerate}
  \item a
  \item a
\end{enumerate}

\begin{enumerate}[resume]
  \item a
  \item a
\end{enumerate}
\end{document}
```

To help answer your question at hand, I suggest to provide a complete example, perhaps to the general q&a forum tex.stackexchange.com rather than the bug tracker here.

**Comment by svlauer** [comment]
Thank you for the fast reply! Now I understand what is going on (I tried to figure it out from the source code, but ...).

(As for my `beamer`-problem, I think I'll be able to figure out how to solve it (or I will ask in an appropriate forum) - I just included it here for some context about why I was asking my question.)

**Comment by muzimuzhi** [comment]
> Now I understand what is going on (I tried to figure it out from the source code, but ...).

Directly reading the source code might be, though not impossible, challenging. "Debugging" utilities like the macro `\tracingall` macro and `unravel` package are helpful here. For example, I used
```tex
\documentclass{article}
\usepackage{enumitem}

\begin{document}
a{\tracingall
\begin{enumerate}
  \item a
  \item a
\end{enumerate}}

\begin{enumerate}[resume]
  \item a
  \item a
\end{enumerate}
\end{document}
```
and then read the output log file and `enumitem.sty` side by side to help find how the resuming info is stored.

**Comment by svlauer** [comment]
Thank you again! This is very helpful. I knew that these "debugging" commands exist, but so far, I've tended to try and figure out the source code by itself. In the future, I will play around with `\tracingcall` etc., instead of just staring at the source code, trying to execute it in my head ...
